In [1]:
import numpy as np

# Step 1: Create a sample dataset (5 samples, 3 features)
data = np.array([
    [2.5, 2.4, 1.0],
    [0.5, 0.7, 1.3],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 1.2],
    [3.1, 3.0, 1.5]
])

# Step 2: Standardize the dataset by subtracting the mean
mean = np.mean(data, axis=0)
data_centered = data - mean

# Step 3: Compute the covariance matrix
cov_matrix = np.cov(data_centered, rowvar=False)

# Step 4: Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

# Step 5: Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# Step 6: Select the top k eigenvectors (principal components)
k = 2  # Reduce to 2 dimensions
principal_components = sorted_eigenvectors[:, :k]

# Step 7: Transform the data to the new space
reduced_data = np.dot(data_centered, principal_components)

# Output results
print("Original Data:\n", data)
print("\nMean of Original Data:\n", mean)
print("\nCentered Data:\n", data_centered)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nEigenvalues:\n", sorted_eigenvalues)
print("\nEigenvectors:\n", sorted_eigenvectors)
print("\nPrincipal Components (Top 2):\n", principal_components)
print("\nReduced Data:\n", reduced_data)


Original Data:
 [[2.5 2.4 1. ]
 [0.5 0.7 1.3]
 [2.2 2.9 0.9]
 [1.9 2.2 1.2]
 [3.1 3.  1.5]]

Mean of Original Data:
 [2.04 2.24 1.18]

Centered Data:
 [[ 0.46  0.16 -0.18]
 [-1.54 -1.54  0.12]
 [ 0.16  0.66 -0.28]
 [-0.14 -0.04  0.02]
 [ 1.06  0.76  0.32]]

Covariance Matrix:
 [[ 0.938   0.8405  0.006 ]
 [ 0.8405  0.853  -0.039 ]
 [ 0.006  -0.039   0.057 ]]

Eigenvalues:
 [1.73737583 0.08773785 0.02288631]

Eigenvectors:
 [[-0.72449859  0.48383043 -0.49092761]
 [-0.68914587 -0.494604    0.52957044]
 [ 0.01340753  0.72199377  0.69176964]]

Principal Components (Top 2):
 [[-0.72449859  0.48383043]
 [-0.68914587 -0.494604  ]
 [ 0.01340753  0.72199377]]

Reduced Data:
 [[-0.44594605  0.01346648]
 [ 2.17862137  0.10323055]
 [-0.57451016 -0.45118403]
 [ 0.12926379 -0.03351222]
 [-1.28742896  0.36799922]]
