In [2]:
import numpy as np

In [3]:
data = np.array([
    [2.5, 2.4, 1.0],
    [0.5, 0.7, 1.3],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 1.2],
    [3.1, 3.0, 1.5]
])

In [4]:
mean = np.mean(data,axis = 0)

In [5]:
data_centered = data - mean
data_centered

array([[ 0.46,  0.16, -0.18],
       [-1.54, -1.54,  0.12],
       [ 0.16,  0.66, -0.28],
       [-0.14, -0.04,  0.02],
       [ 1.06,  0.76,  0.32]])

In [8]:
cov_mat = np.cov(data_centered, rowvar=False)
cov_mat

array([[ 0.938 ,  0.8405,  0.006 ],
       [ 0.8405,  0.853 , -0.039 ],
       [ 0.006 , -0.039 ,  0.057 ]])

In [9]:
eval,evec = np.linalg.eigh(cov_mat)

In [10]:
eval

array([0.02288631, 0.08773785, 1.73737583])

In [11]:
evec

array([[-0.49092761,  0.48383043, -0.72449859],
       [ 0.52957044, -0.494604  , -0.68914587],
       [ 0.69176964,  0.72199377,  0.01340753]])

In [14]:
sorted_eval_idx = np.argsort(eval)[::-1]
sorted_eval_idx

array([2, 1, 0])

In [19]:
sorted_evec = evec[:,sorted_eval_idx]
sorted_evec

array([[-0.72449859,  0.48383043, -0.49092761],
       [-0.68914587, -0.494604  ,  0.52957044],
       [ 0.01340753,  0.72199377,  0.69176964]])

In [27]:
k=2
pca = sorted_evec[:,:k]
pca

array([[-0.72449859,  0.48383043],
       [-0.68914587, -0.494604  ],
       [ 0.01340753,  0.72199377]])

In [29]:
np.dot(data_centered,pca)

array([[-0.44594605,  0.01346648],
       [ 2.17862137,  0.10323055],
       [-0.57451016, -0.45118403],
       [ 0.12926379, -0.03351222],
       [-1.28742896,  0.36799922]])