In [1]:
import numpy as np

In [3]:
data = np.array([
    [2.5, 2.4, 1.0],
    [0.5, 0.7, 1.3],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 1.2],
    [3.1, 3.0, 1.5]
])

In [5]:
mean = np.mean(data, axis = 0)
mean

array([2.04, 2.24, 1.18])

In [7]:
data_centered = data - mean
data_centered

array([[ 0.46,  0.16, -0.18],
       [-1.54, -1.54,  0.12],
       [ 0.16,  0.66, -0.28],
       [-0.14, -0.04,  0.02],
       [ 1.06,  0.76,  0.32]])

In [11]:
covariance_matrix = np.cov(data_centered, rowvar=False)
covariance_matrix

array([[ 0.938 ,  0.8405,  0.006 ],
       [ 0.8405,  0.853 , -0.039 ],
       [ 0.006 , -0.039 ,  0.057 ]])

In [13]:
eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)
eigenvalues

array([0.02288631, 0.08773785, 1.73737583])

In [14]:
eigenvectors

array([[-0.49092761,  0.48383043, -0.72449859],
       [ 0.52957044, -0.494604  , -0.68914587],
       [ 0.69176964,  0.72199377,  0.01340753]])

In [16]:
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_indices # sort the indices in reverse order

array([2, 1, 0])

In [17]:
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvalues

array([1.73737583, 0.08773785, 0.02288631])

In [18]:
sorted_eigenvectors = eigenvectors[:, sorted_indices]
sorted_eigenvectors

array([[-0.72449859,  0.48383043, -0.49092761],
       [-0.68914587, -0.494604  ,  0.52957044],
       [ 0.01340753,  0.72199377,  0.69176964]])

In [20]:
k = 2  # Reduce to 2 dimensions
principal_components = sorted_eigenvectors[:, :k]
principal_components

array([[-0.72449859,  0.48383043],
       [-0.68914587, -0.494604  ],
       [ 0.01340753,  0.72199377]])

In [21]:
reduced_data = np.dot(data_centered, principal_components)
reduced_data

array([[-0.44594605,  0.01346648],
       [ 2.17862137,  0.10323055],
       [-0.57451016, -0.45118403],
       [ 0.12926379, -0.03351222],
       [-1.28742896,  0.36799922]])